#constants used by all scripts

#command thread states
CMD_STATE_INIT = 0
CMD_STATE_STARTED = 1
CMD_STATE_EXPIRED = 2


CMD_TYPE_CC = 'cc'


CONDITION_BOOL = 1
CONDITION_COLOR = 2
CONDITION_TIME = 3
CONDITION_ITERATE = 4