{
    "commands":[
        {
            "type":"wait",
            "time":"5"
        }
        {
            "type":"cc",
            "color":"{x:ABCDEF}"
        }
        {
            "type":"wait",
            "time":"5"
        }
        {
            "type":"fade",
            "time":"{r:5,10}",
            "end":"{f:1,1,1}"
        }
    ]
}

