{
    "commands":[
        {
            "type":"loop",
            "condition":"{i:5}",
            "commands":
            [
                {
                    "type":"cc",
                    "color":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"wait",
                    "time":"{r:0.1,10}"
                }
            ]
        }
    ]
}

