{
    "commands":[
        {
            "type":"loop",
            "condition":"{t:{r:5,10}}",
            "commands":
            [
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                },
                {
                    "type":"fade",
                    "time":"{r:10,20}",
                    "end":"{r:0-1,0-1,0-1}"
                }
            ]
        }
    ]
}

